mod_version=26.1.2
group=com.hyfata
java_version=25
minecraft_version=26.1.2
mod_name=KORChat
artifact_id=korchat
mod_author=Najoan
mod_id=koreanpatch
license=LGPL-3.0
credits=Shihyeon
description=KORChat is a Minecraft 26.1.2 Korean chat and input mod forked from Korean Patch.
minecraft_version_range=[26.1.2, 26.2)
fabric_version_range=>=26.1.2 <26.2
neo_form_version=26.1.2-1
cloth_config=21.11.152
yacl_version=3.8.1+1.21.11
fabric_version=0.145.4+26.1.2
fabric_loader_version=0.18.4
neoforge_version=26.1.2.7-beta
neoforge_loader_version_range=[4,)
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
modmenu_version=17.0.0-alpha.1
command_block_ide_version=0.4.12
better_command_block_ui_version=2Ma93oxi
easy_anvils_version_fabric=RRPRJ01x
easy_anvils_version_neo=aOrQpmtS
axiom_version=TibxxJrx
xaeros_minimap_fabric=NDNq9HeR
xaeros_minimap_neo=ywIsFrc2
xaeros_world_map_fabric=cEKMweJE
xaeros_world_map_neo=Nm3A673b
rei_fabric=CkkZK8ao
rei_neo=rCAaJej0
