plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        data {
            clientData()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    compileOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config}"
    compileOnly "maven.modrinth:yacl:${project.yacl_version}-neoforge"
    compileOnly "maven.modrinth:easy-anvils:${project.easy_anvils_version_neo}"
    compileOnly "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_neo}"
    compileOnly "maven.modrinth:xaeros-world-map:${project.xaeros_world_map_neo}"
    compileOnly "maven.modrinth:rei:${project.rei_neo}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    exclude 'com/hyfata/najoan/koreanpatch/config/yacl/**'
    exclude 'com/hyfata/najoan/koreanpatch/mixin/accessor/GuiGraphicsAccessor.java'
    exclude 'com/hyfata/najoan/koreanpatch/mixin/indicator/**'
    exclude 'com/hyfata/najoan/koreanpatch/mixin/mods/**'
    exclude 'com/hyfata/najoan/koreanpatch/util/YACLUtil.java'
    exclude 'com/hyfata/najoan/koreanpatch/util/minecraft/RenderUtil.java'
    exclude 'com/hyfata/najoan/koreanpatch/util/minecraft/gui/**'
    exclude 'com/hyfata/najoan/koreanpatch/wrapper/WrapperREITextField.java'
}

sourceSets.main.java {
    exclude 'com/hyfata/najoan/koreanpatch/mixin/mods/**'
    exclude 'com/hyfata/najoan/koreanpatch/wrapper/WrapperREITextField.java'
}
